version: "3"

networks:
  study_projects:
    external: true

services:
  api:
    build:
      context: .
      dockerfile: ./Docker/api/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    networks:
      - study_projects
  